"""Regenerate FIGURES.md: which slide uses which figure, and where it comes from.

Run from the repository root:  python tools/make_figure_map.py
"""
import io
import os
import re
import subprocess

DECKS = ["math1", "math2", "math3", "math4", "math5"]
INCLUDE = re.compile(r"includegraphics\[[^\]]*\]\{([^}]+)\}")
FRAME = re.compile(r"\\begin\{frame\}(?:\[[a-z]\])?\{(.*?)\}", re.S)
GENERATED = re.compile(r'save_vector_pair\(fig,\s*"([^"]+)"')


def generated_by(deck):
    path = os.path.join("source", deck, "regenerate_vector_plots.py")
    if not os.path.exists(path):
        return set()
    return set(GENERATED.findall(io.open(path, encoding="utf-8").read()))


def figures_with_slides(deck):
    """Pair every \\includegraphics with the frame title it sits in."""
    tex = io.open(os.path.join("source", deck, "main.tex"), encoding="utf-8").read()
    frames = [(m.start(), m.group(1)) for m in FRAME.finditer(tex)]
    rows = []
    for m in INCLUDE.finditer(tex):
        title = next((t for pos, t in reversed(frames) if pos < m.start()), "?")
        rows.append((re.sub(r"\s+", " ", title).strip(), m.group(1)))
    return rows


def page_count(pdf):
    try:
        out = subprocess.run(["pdfinfo", pdf], capture_output=True, text=True).stdout
        return re.search(r"^Pages:\s+(\d+)", out, re.M).group(1)
    except Exception:
        return "?"


lines = [
    "# Figure map",
    "",
    "Generated by `tools/make_figure_map.py` -- do not edit by hand.",
    "",
    "Every figure used in the slides, the frame it appears on, and where it",
    "comes from. **generated** means the figure is drawn by that deck's own",
    "`regenerate_vector_plots.py` and can be reproduced from source; anything",
    "else is a third-party excerpt reproduced under fair use for teaching.",
    "",
]

for deck in DECKS:
    if not os.path.exists(os.path.join("source", deck, "main.tex")):
        continue
    gen = generated_by(deck)
    rows = figures_with_slides(deck)
    pdf = os.path.join("output", "pdf", deck + ".pdf")
    lines += [
        f"## {deck} ({page_count(pdf)} slides)",
        "",
        "| slide | figure | provenance |",
        "| --- | --- | --- |",
    ]
    for title, fig in rows:
        stem = fig.rsplit(".", 1)[0]
        if stem in gen:
            origin = "generated"
        elif fig.endswith(".jpg"):
            origin = "book cover"
        else:
            origin = "scanned page excerpt"
        lines.append(f"| {title} | `{fig}` | {origin} |")
    unused = sorted(gen - {f.rsplit(".", 1)[0] for _, f in rows})
    if unused:
        lines += ["", "Generated but not currently used: "
                  + ", ".join(f"`{u}`" for u in unused) + "."]
    lines.append("")

io.open("FIGURES.md", "w", encoding="utf-8", newline="").write("\n".join(lines))
print("FIGURES.md written")
