"""Generate source/palette.tex from source/palette.py.

Run from the repository root:  python tools/make_palette.py
"""
import io
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "source"))
from palette import PALETTE  # noqa: E402

lines = [
    "% Generated by tools/make_palette.py from source/palette.py.",
    "% Do not edit by hand: edit palette.py and regenerate.",
]
lines += [
    r"\definecolor{%s}{HTML}{%s}" % (name, value.lstrip("#"))
    for name, value in PALETTE.items()
]
out = ROOT / "source" / "palette.tex"
io.open(out, "w", encoding="utf-8", newline="").write("\n".join(lines) + "\n")
print("wrote", out.relative_to(ROOT))
